server:
  port: 8000

spring:
  application:
    name: short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: short-link_project-service_stats-save_pg_donny22
    topic: short-link_project-service_topic_donny22
    send-message-timeout: 2000
    retry-times-when-send-async-failed: 1
    retry-times-when-send-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg_donny22